# coding: utf-8

"""
    portfolio-services Api Doc

    Rest APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: sales@marketsimplified.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrderTrail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'limit_price': 'float',
        'lupdate_date_time': 'str',
        'ord_desc': 'str',
        'ord_type': 'str',
        'ord_validity': 'str',
        'modified_by': 'str',
        'status': 'str',
        'rej_reason': 'str',
        'avg_price': 'float',
        'qty': 'int',
        'pending_qty': 'int',
        'dis_qty': 'int',
        'price': 'float',
        'trigger_price': 'float',
        'exc': 'str',
        'prd_type': 'str',
        'ord_id': 'str',
        'exch_ord_id': 'str',
        'ord_action': 'str',
        'current_ord_status': 'str',
        'traded_qty': 'int',
        'symbol': 'SymbolDto'
    }

    attribute_map = {
        'limit_price': 'limitPrice',
        'lupdate_date_time': 'lupdateDateTime',
        'ord_desc': 'ordDesc',
        'ord_type': 'ordType',
        'ord_validity': 'ordValidity',
        'modified_by': 'modifiedBy',
        'status': 'status',
        'rej_reason': 'rejReason',
        'avg_price': 'avgPrice',
        'qty': 'qty',
        'pending_qty': 'pendingQty',
        'dis_qty': 'disQty',
        'price': 'price',
        'trigger_price': 'triggerPrice',
        'exc': 'exc',
        'prd_type': 'prdType',
        'ord_id': 'ordId',
        'exch_ord_id': 'exchOrdId',
        'ord_action': 'ordAction',
        'current_ord_status': 'currentOrdStatus',
        'traded_qty': 'tradedQty',
        'symbol': 'symbol'
    }

    def __init__(self, limit_price=None, lupdate_date_time=None, ord_desc=None, ord_type=None, ord_validity=None, modified_by=None, status=None, rej_reason=None, avg_price=None, qty=None, pending_qty=None, dis_qty=None, price=None, trigger_price=None, exc=None, prd_type=None, ord_id=None, exch_ord_id=None, ord_action=None, current_ord_status=None, traded_qty=None, symbol=None):  # noqa: E501
        """OrderTrail - a model defined in Swagger"""  # noqa: E501
        self._limit_price = None
        self._lupdate_date_time = None
        self._ord_desc = None
        self._ord_type = None
        self._ord_validity = None
        self._modified_by = None
        self._status = None
        self._rej_reason = None
        self._avg_price = None
        self._qty = None
        self._pending_qty = None
        self._dis_qty = None
        self._price = None
        self._trigger_price = None
        self._exc = None
        self._prd_type = None
        self._ord_id = None
        self._exch_ord_id = None
        self._ord_action = None
        self._current_ord_status = None
        self._traded_qty = None
        self._symbol = None
        self.discriminator = None
        if limit_price is not None:
            self.limit_price = limit_price
        if lupdate_date_time is not None:
            self.lupdate_date_time = lupdate_date_time
        if ord_desc is not None:
            self.ord_desc = ord_desc
        if ord_type is not None:
            self.ord_type = ord_type
        if ord_validity is not None:
            self.ord_validity = ord_validity
        if modified_by is not None:
            self.modified_by = modified_by
        if status is not None:
            self.status = status
        if rej_reason is not None:
            self.rej_reason = rej_reason
        if avg_price is not None:
            self.avg_price = avg_price
        if qty is not None:
            self.qty = qty
        if pending_qty is not None:
            self.pending_qty = pending_qty
        if dis_qty is not None:
            self.dis_qty = dis_qty
        if price is not None:
            self.price = price
        if trigger_price is not None:
            self.trigger_price = trigger_price
        if exc is not None:
            self.exc = exc
        if prd_type is not None:
            self.prd_type = prd_type
        if ord_id is not None:
            self.ord_id = ord_id
        if exch_ord_id is not None:
            self.exch_ord_id = exch_ord_id
        if ord_action is not None:
            self.ord_action = ord_action
        if current_ord_status is not None:
            self.current_ord_status = current_ord_status
        if traded_qty is not None:
            self.traded_qty = traded_qty
        if symbol is not None:
            self.symbol = symbol

    @property
    def limit_price(self):
        """Gets the limit_price of this OrderTrail.  # noqa: E501


        :return: The limit_price of this OrderTrail.  # noqa: E501
        :rtype: float
        """
        return self._limit_price

    @limit_price.setter
    def limit_price(self, limit_price):
        """Sets the limit_price of this OrderTrail.


        :param limit_price: The limit_price of this OrderTrail.  # noqa: E501
        :type: float
        """

        self._limit_price = limit_price

    @property
    def lupdate_date_time(self):
        """Gets the lupdate_date_time of this OrderTrail.  # noqa: E501


        :return: The lupdate_date_time of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._lupdate_date_time

    @lupdate_date_time.setter
    def lupdate_date_time(self, lupdate_date_time):
        """Sets the lupdate_date_time of this OrderTrail.


        :param lupdate_date_time: The lupdate_date_time of this OrderTrail.  # noqa: E501
        :type: str
        """

        self._lupdate_date_time = lupdate_date_time

    @property
    def ord_desc(self):
        """Gets the ord_desc of this OrderTrail.  # noqa: E501


        :return: The ord_desc of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._ord_desc

    @ord_desc.setter
    def ord_desc(self, ord_desc):
        """Sets the ord_desc of this OrderTrail.


        :param ord_desc: The ord_desc of this OrderTrail.  # noqa: E501
        :type: str
        """

        self._ord_desc = ord_desc

    @property
    def ord_type(self):
        """Gets the ord_type of this OrderTrail.  # noqa: E501


        :return: The ord_type of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._ord_type

    @ord_type.setter
    def ord_type(self, ord_type):
        """Sets the ord_type of this OrderTrail.


        :param ord_type: The ord_type of this OrderTrail.  # noqa: E501
        :type: str
        """
        allowed_values = ["Market", "Limit", "Stop", "Stop-loss", "SL-M", "SL", "None"]  # noqa: E501
        if ord_type not in allowed_values:
            raise ValueError(
                "Invalid value for `ord_type` ({0}), must be one of {1}"  # noqa: E501
                .format(ord_type, allowed_values)
            )

        self._ord_type = ord_type

    @property
    def ord_validity(self):
        """Gets the ord_validity of this OrderTrail.  # noqa: E501


        :return: The ord_validity of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._ord_validity

    @ord_validity.setter
    def ord_validity(self, ord_validity):
        """Sets the ord_validity of this OrderTrail.


        :param ord_validity: The ord_validity of this OrderTrail.  # noqa: E501
        :type: str
        """
        allowed_values = ["DAY", "IOC", "GMT", "GTC", "AMO", "GTD", "NONE"]  # noqa: E501
        if ord_validity not in allowed_values:
            raise ValueError(
                "Invalid value for `ord_validity` ({0}), must be one of {1}"  # noqa: E501
                .format(ord_validity, allowed_values)
            )

        self._ord_validity = ord_validity

    @property
    def modified_by(self):
        """Gets the modified_by of this OrderTrail.  # noqa: E501


        :return: The modified_by of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._modified_by

    @modified_by.setter
    def modified_by(self, modified_by):
        """Sets the modified_by of this OrderTrail.


        :param modified_by: The modified_by of this OrderTrail.  # noqa: E501
        :type: str
        """

        self._modified_by = modified_by

    @property
    def status(self):
        """Gets the status of this OrderTrail.  # noqa: E501


        :return: The status of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OrderTrail.


        :param status: The status of this OrderTrail.  # noqa: E501
        :type: str
        """
        allowed_values = ["Executed", "Pending", "Cancelled", "Transit", "Rejected", "Requested", "None"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def rej_reason(self):
        """Gets the rej_reason of this OrderTrail.  # noqa: E501


        :return: The rej_reason of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._rej_reason

    @rej_reason.setter
    def rej_reason(self, rej_reason):
        """Sets the rej_reason of this OrderTrail.


        :param rej_reason: The rej_reason of this OrderTrail.  # noqa: E501
        :type: str
        """

        self._rej_reason = rej_reason

    @property
    def avg_price(self):
        """Gets the avg_price of this OrderTrail.  # noqa: E501


        :return: The avg_price of this OrderTrail.  # noqa: E501
        :rtype: float
        """
        return self._avg_price

    @avg_price.setter
    def avg_price(self, avg_price):
        """Sets the avg_price of this OrderTrail.


        :param avg_price: The avg_price of this OrderTrail.  # noqa: E501
        :type: float
        """

        self._avg_price = avg_price

    @property
    def qty(self):
        """Gets the qty of this OrderTrail.  # noqa: E501


        :return: The qty of this OrderTrail.  # noqa: E501
        :rtype: int
        """
        return self._qty

    @qty.setter
    def qty(self, qty):
        """Sets the qty of this OrderTrail.


        :param qty: The qty of this OrderTrail.  # noqa: E501
        :type: int
        """

        self._qty = qty

    @property
    def pending_qty(self):
        """Gets the pending_qty of this OrderTrail.  # noqa: E501


        :return: The pending_qty of this OrderTrail.  # noqa: E501
        :rtype: int
        """
        return self._pending_qty

    @pending_qty.setter
    def pending_qty(self, pending_qty):
        """Sets the pending_qty of this OrderTrail.


        :param pending_qty: The pending_qty of this OrderTrail.  # noqa: E501
        :type: int
        """

        self._pending_qty = pending_qty

    @property
    def dis_qty(self):
        """Gets the dis_qty of this OrderTrail.  # noqa: E501


        :return: The dis_qty of this OrderTrail.  # noqa: E501
        :rtype: int
        """
        return self._dis_qty

    @dis_qty.setter
    def dis_qty(self, dis_qty):
        """Sets the dis_qty of this OrderTrail.


        :param dis_qty: The dis_qty of this OrderTrail.  # noqa: E501
        :type: int
        """

        self._dis_qty = dis_qty

    @property
    def price(self):
        """Gets the price of this OrderTrail.  # noqa: E501


        :return: The price of this OrderTrail.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this OrderTrail.


        :param price: The price of this OrderTrail.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def trigger_price(self):
        """Gets the trigger_price of this OrderTrail.  # noqa: E501


        :return: The trigger_price of this OrderTrail.  # noqa: E501
        :rtype: float
        """
        return self._trigger_price

    @trigger_price.setter
    def trigger_price(self, trigger_price):
        """Sets the trigger_price of this OrderTrail.


        :param trigger_price: The trigger_price of this OrderTrail.  # noqa: E501
        :type: float
        """

        self._trigger_price = trigger_price

    @property
    def exc(self):
        """Gets the exc of this OrderTrail.  # noqa: E501


        :return: The exc of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._exc

    @exc.setter
    def exc(self, exc):
        """Sets the exc of this OrderTrail.


        :param exc: The exc of this OrderTrail.  # noqa: E501
        :type: str
        """
        allowed_values = ["NSE", "BSE", "NFO", "BFO", "CDS", "BCD", "MCXSX", "MCX", "NCO", "BCO", "ICEX"]  # noqa: E501
        if exc not in allowed_values:
            raise ValueError(
                "Invalid value for `exc` ({0}), must be one of {1}"  # noqa: E501
                .format(exc, allowed_values)
            )

        self._exc = exc

    @property
    def prd_type(self):
        """Gets the prd_type of this OrderTrail.  # noqa: E501


        :return: The prd_type of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._prd_type

    @prd_type.setter
    def prd_type(self, prd_type):
        """Sets the prd_type of this OrderTrail.


        :param prd_type: The prd_type of this OrderTrail.  # noqa: E501
        :type: str
        """
        allowed_values = ["CASH", "MTF", "INTRADAY", "MARGIN", "SHORTSELL", "COVER_ORDER", "BRACKET_ORDER", "NRML", "TNC", "DELIVERY", "NONE"]  # noqa: E501
        if prd_type not in allowed_values:
            raise ValueError(
                "Invalid value for `prd_type` ({0}), must be one of {1}"  # noqa: E501
                .format(prd_type, allowed_values)
            )

        self._prd_type = prd_type

    @property
    def ord_id(self):
        """Gets the ord_id of this OrderTrail.  # noqa: E501


        :return: The ord_id of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._ord_id

    @ord_id.setter
    def ord_id(self, ord_id):
        """Sets the ord_id of this OrderTrail.


        :param ord_id: The ord_id of this OrderTrail.  # noqa: E501
        :type: str
        """

        self._ord_id = ord_id

    @property
    def exch_ord_id(self):
        """Gets the exch_ord_id of this OrderTrail.  # noqa: E501


        :return: The exch_ord_id of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._exch_ord_id

    @exch_ord_id.setter
    def exch_ord_id(self, exch_ord_id):
        """Sets the exch_ord_id of this OrderTrail.


        :param exch_ord_id: The exch_ord_id of this OrderTrail.  # noqa: E501
        :type: str
        """

        self._exch_ord_id = exch_ord_id

    @property
    def ord_action(self):
        """Gets the ord_action of this OrderTrail.  # noqa: E501


        :return: The ord_action of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._ord_action

    @ord_action.setter
    def ord_action(self, ord_action):
        """Sets the ord_action of this OrderTrail.


        :param ord_action: The ord_action of this OrderTrail.  # noqa: E501
        :type: str
        """
        allowed_values = ["BUY", "SELL", "SHORT", "NONE"]  # noqa: E501
        if ord_action not in allowed_values:
            raise ValueError(
                "Invalid value for `ord_action` ({0}), must be one of {1}"  # noqa: E501
                .format(ord_action, allowed_values)
            )

        self._ord_action = ord_action

    @property
    def current_ord_status(self):
        """Gets the current_ord_status of this OrderTrail.  # noqa: E501


        :return: The current_ord_status of this OrderTrail.  # noqa: E501
        :rtype: str
        """
        return self._current_ord_status

    @current_ord_status.setter
    def current_ord_status(self, current_ord_status):
        """Sets the current_ord_status of this OrderTrail.


        :param current_ord_status: The current_ord_status of this OrderTrail.  # noqa: E501
        :type: str
        """

        self._current_ord_status = current_ord_status

    @property
    def traded_qty(self):
        """Gets the traded_qty of this OrderTrail.  # noqa: E501


        :return: The traded_qty of this OrderTrail.  # noqa: E501
        :rtype: int
        """
        return self._traded_qty

    @traded_qty.setter
    def traded_qty(self, traded_qty):
        """Sets the traded_qty of this OrderTrail.


        :param traded_qty: The traded_qty of this OrderTrail.  # noqa: E501
        :type: int
        """

        self._traded_qty = traded_qty

    @property
    def symbol(self):
        """Gets the symbol of this OrderTrail.  # noqa: E501


        :return: The symbol of this OrderTrail.  # noqa: E501
        :rtype: SymbolDto
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this OrderTrail.


        :param symbol: The symbol of this OrderTrail.  # noqa: E501
        :type: SymbolDto
        """

        self._symbol = symbol

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderTrail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderTrail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
