# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class FundsSucessDataALL(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'allbrokerage_prsnt': 'str',
        'allco_mrgn_reqd': 'str',
        'allmf_amt': 'str',
        'allvar_margn': 'str',
        'allcollateral_val': 'str',
        'allrealized_pnl': 'str',
        'allelm_margn': 'str',
        'allloss_limit': 'str',
        'allcnc_real_mtm': 'str',
        'allcnc_elmr_margn': 'str',
        'allbooked_pnl': 'str',
        'allexp_margn': 'str',
        'allttl_cash_bal': 'str',
        'allcnc_un_real_mtm': 'str',
        'allremarks': 'str',
        'allstock_cfs': 'str',
        'allcnc_mrgn_used': 'str',
        'allbuypwr': 'str',
        'all_fd': 'str',
        'allcnc_var_margn': 'str',
        'allpremium_prsnt': 'str',
        'alldebits': 'str',
        'allcategory': 'str',
        'alldirct_colatrl': 'str',
        'allmargn_used': 'str',
        'all_view_unreal_mtm': 'str',
        'allt1_gross_collatrl': 'str',
        'allcnc_credit': 'str',
        'allmfss_amnt_used': 'str',
        'allsegment': 'str',
        'alladhoc_margn': 'str',
        'alldelivry_mrgn': 'str',
        'alllien': 'str',
        'allmrgn_srp_bsk_prsnt': 'str',
        'allsell_exp': 'str',
        'alladd_pre_exp_mrgn_prsnt': 'str',
        'alltotal_collateral_val': 'str',
        'alladhoc_srp_mrgn': 'str',
        'allfo_exp_mgn_nrml_prsnt': 'str',
        'allpayout': 'str',
        'allreal_loss': 'str',
        'allnet_cash_avail': 'str',
        'allmargn_blocked': 'str',
        'allutilized_margin': 'str',
        'allcm_mrgn_cnc_prsnt': 'str',
        'alltender_mrgn_prsnt': 'str',
        'allnotnal_cash': 'str',
        'allscrp_bskt_mrgn': 'str',
        'allgrosscoltrl': 'str',
        'allun_real_m2_m_loss': 'str',
        'allgross_exp': 'str',
        'allval_delry': 'str',
        'allunrealized_pnl': 'str',
        'alladd_mrgn_prsnt': 'str',
        'allbo_mrgn_reqd': 'str',
        'allcm_mrgn_mis_prct': 'str',
        'allmultiplier': 'str',
        'allcredits': 'str',
        'allunreal_mtm': 'str',
        'allpayin': 'str',
        'allnfo_sprd_benefit': 'str',
        'allcash_bal': 'str',
        'allremarks_amnt': 'str',
        'allcur_spn_mrg_nrml_prsnt': 'str',
        'allunbook_pnl': 'str',
        'allcnc_brk_prst': 'str',
        'allun_real_loss': 'str',
        'allcur_exp_mrg_mis_prsnt': 'str',
        'allfo_exp_mrgn_mis_prsnt': 'str',
        'allbuy_exp': 'str',
        'allcdssprd_benefits': 'str',
        'all_un_setld_credit': 'str',
        'allspan_mrgn_nrml': 'str',
        'allreal_pnl': 'str',
        'allspan_mrgn_mis': 'str',
        'allbrnch_adhoc': 'str',
        'allipo_amt': 'str',
        'alladhoc': 'str',
        'allturnover': 'str',
        'allreal_mtm': 'str',
        'allcur_exp_mrg_nrml_prsnt': 'str',
        'allspan_margn': 'str',
        'allreal_m2_m_loss': 'str'
    }

    attribute_map = {
        'allbrokerage_prsnt': 'allbrokeragePrsnt',
        'allco_mrgn_reqd': 'allcoMrgnReqd',
        'allmf_amt': 'allmfAmt',
        'allvar_margn': 'allvarMargn',
        'allcollateral_val': 'allcollateralVal',
        'allrealized_pnl': 'allrealizedPNL',
        'allelm_margn': 'allelmMargn',
        'allloss_limit': 'alllossLimit',
        'allcnc_real_mtm': 'allcncRealMTM',
        'allcnc_elmr_margn': 'allcncElmrMargn',
        'allbooked_pnl': 'allbookedPnl',
        'allexp_margn': 'allexpMargn',
        'allttl_cash_bal': 'allttlCashBal',
        'allcnc_un_real_mtm': 'allcncUnRealMTM',
        'allremarks': 'allremarks',
        'allstock_cfs': 'allstockCFS',
        'allcnc_mrgn_used': 'allcncMrgnUsed',
        'allbuypwr': 'allbuypwr',
        'all_fd': 'allFD',
        'allcnc_var_margn': 'allcncVarMargn',
        'allpremium_prsnt': 'allpremiumPrsnt',
        'alldebits': 'alldebits',
        'allcategory': 'allcategory',
        'alldirct_colatrl': 'alldirctColatrl',
        'allmargn_used': 'allmargnUsed',
        'all_view_unreal_mtm': 'allViewUnrealMTM',
        'allt1_gross_collatrl': 'allt1GrossCollatrl',
        'allcnc_credit': 'allcncCredit',
        'allmfss_amnt_used': 'allmfssAmntUsed',
        'allsegment': 'allsegment',
        'alladhoc_margn': 'alladhocMargn',
        'alldelivry_mrgn': 'alldelivryMrgn',
        'alllien': 'alllien',
        'allmrgn_srp_bsk_prsnt': 'allmrgnSrpBskPrsnt',
        'allsell_exp': 'allsellExp',
        'alladd_pre_exp_mrgn_prsnt': 'alladdPreExpMrgnPrsnt',
        'alltotal_collateral_val': 'alltotalCollateralVal',
        'alladhoc_srp_mrgn': 'alladhocSrpMrgn',
        'allfo_exp_mgn_nrml_prsnt': 'allfoExpMgnNrmlPrsnt',
        'allpayout': 'allpayout',
        'allreal_loss': 'allrealLoss',
        'allnet_cash_avail': 'allnetCashAvail',
        'allmargn_blocked': 'allmargnBlocked',
        'allutilized_margin': 'allutilizedMargin',
        'allcm_mrgn_cnc_prsnt': 'allcmMrgnCncPrsnt',
        'alltender_mrgn_prsnt': 'alltenderMrgnPrsnt',
        'allnotnal_cash': 'allnotnalCash',
        'allscrp_bskt_mrgn': 'allscrpBsktMrgn',
        'allgrosscoltrl': 'allgrosscoltrl',
        'allun_real_m2_m_loss': 'allunRealM2MLoss',
        'allgross_exp': 'allgrossExp',
        'allval_delry': 'allvalDelry',
        'allunrealized_pnl': 'allunrealizedPNL',
        'alladd_mrgn_prsnt': 'alladdMrgnPrsnt',
        'allbo_mrgn_reqd': 'allboMrgnReqd',
        'allcm_mrgn_mis_prct': 'allcmMrgnMisPrct',
        'allmultiplier': 'allmultiplier',
        'allcredits': 'allcredits',
        'allunreal_mtm': 'allunrealMTM',
        'allpayin': 'allpayin',
        'allnfo_sprd_benefit': 'allnfoSprdBenefit',
        'allcash_bal': 'allcashBal',
        'allremarks_amnt': 'allremarksAmnt',
        'allcur_spn_mrg_nrml_prsnt': 'allcurSpnMrgNrmlPrsnt',
        'allunbook_pnl': 'allunbookPNL',
        'allcnc_brk_prst': 'allcncBrkPrst',
        'allun_real_loss': 'allunRealLoss',
        'allcur_exp_mrg_mis_prsnt': 'allcurExpMrgMisPrsnt',
        'allfo_exp_mrgn_mis_prsnt': 'allfoExpMrgnMisPrsnt',
        'allbuy_exp': 'allbuyExp',
        'allcdssprd_benefits': 'allcdssprdBenefits',
        'all_un_setld_credit': 'allUnSetldCredit',
        'allspan_mrgn_nrml': 'allspanMrgnNRML',
        'allreal_pnl': 'allrealPNL',
        'allspan_mrgn_mis': 'allspanMrgnMIS',
        'allbrnch_adhoc': 'allbrnchAdhoc',
        'allipo_amt': 'allipoAmt',
        'alladhoc': 'alladhoc',
        'allturnover': 'allturnover',
        'allreal_mtm': 'allrealMTM',
        'allcur_exp_mrg_nrml_prsnt': 'allcurExpMrgNrmlPrsnt',
        'allspan_margn': 'allspanMargn',
        'allreal_m2_m_loss': 'allrealM2MLoss'
    }

    def __init__(self, allbrokerage_prsnt=None, allco_mrgn_reqd=None, allmf_amt=None, allvar_margn=None,
                 allcollateral_val=None, allrealized_pnl=None, allelm_margn=None, allloss_limit=None,
                 allcnc_real_mtm=None, allcnc_elmr_margn=None, allbooked_pnl=None, allexp_margn=None,
                 allttl_cash_bal=None, allcnc_un_real_mtm=None, allremarks=None, allstock_cfs=None,
                 allcnc_mrgn_used=None, allbuypwr=None, all_fd=None, allcnc_var_margn=None, allpremium_prsnt=None,
                 alldebits=None, allcategory=None, alldirct_colatrl=None, allmargn_used=None, all_view_unreal_mtm=None,
                 allt1_gross_collatrl=None, allcnc_credit=None, allmfss_amnt_used=None, allsegment=None,
                 alladhoc_margn=None, alldelivry_mrgn=None, alllien=None, allmrgn_srp_bsk_prsnt=None, allsell_exp=None,
                 alladd_pre_exp_mrgn_prsnt=None, alltotal_collateral_val=None, alladhoc_srp_mrgn=None,
                 allfo_exp_mgn_nrml_prsnt=None, allpayout=None, allreal_loss=None, allnet_cash_avail=None,
                 allmargn_blocked=None, allutilized_margin=None, allcm_mrgn_cnc_prsnt=None, alltender_mrgn_prsnt=None,
                 allnotnal_cash=None, allscrp_bskt_mrgn=None, allgrosscoltrl=None, allun_real_m2_m_loss=None,
                 allgross_exp=None, allval_delry=None, allunrealized_pnl=None, alladd_mrgn_prsnt=None,
                 allbo_mrgn_reqd=None, allcm_mrgn_mis_prct=None, allmultiplier=None, allcredits=None,
                 allunreal_mtm=None, allpayin=None, allnfo_sprd_benefit=None, allcash_bal=None, allremarks_amnt=None,
                 allcur_spn_mrg_nrml_prsnt=None, allunbook_pnl=None, allcnc_brk_prst=None, allun_real_loss=None,
                 allcur_exp_mrg_mis_prsnt=None, allfo_exp_mrgn_mis_prsnt=None, allbuy_exp=None,
                 allcdssprd_benefits=None, all_un_setld_credit=None, allspan_mrgn_nrml=None, allreal_pnl=None,
                 allspan_mrgn_mis=None, allbrnch_adhoc=None, allipo_amt=None, alladhoc=None, allturnover=None,
                 allreal_mtm=None, allcur_exp_mrg_nrml_prsnt=None, allspan_margn=None,
                 allreal_m2_m_loss=None):  # noqa: E501
        """FundsSucessDataALL - a model defined in Swagger"""  # noqa: E501
        self._allbrokerage_prsnt = None
        self._allco_mrgn_reqd = None
        self._allmf_amt = None
        self._allvar_margn = None
        self._allcollateral_val = None
        self._allrealized_pnl = None
        self._allelm_margn = None
        self._allloss_limit = None
        self._allcnc_real_mtm = None
        self._allcnc_elmr_margn = None
        self._allbooked_pnl = None
        self._allexp_margn = None
        self._allttl_cash_bal = None
        self._allcnc_un_real_mtm = None
        self._allremarks = None
        self._allstock_cfs = None
        self._allcnc_mrgn_used = None
        self._allbuypwr = None
        self._all_fd = None
        self._allcnc_var_margn = None
        self._allpremium_prsnt = None
        self._alldebits = None
        self._allcategory = None
        self._alldirct_colatrl = None
        self._allmargn_used = None
        self._all_view_unreal_mtm = None
        self._allt1_gross_collatrl = None
        self._allcnc_credit = None
        self._allmfss_amnt_used = None
        self._allsegment = None
        self._alladhoc_margn = None
        self._alldelivry_mrgn = None
        self._alllien = None
        self._allmrgn_srp_bsk_prsnt = None
        self._allsell_exp = None
        self._alladd_pre_exp_mrgn_prsnt = None
        self._alltotal_collateral_val = None
        self._alladhoc_srp_mrgn = None
        self._allfo_exp_mgn_nrml_prsnt = None
        self._allpayout = None
        self._allreal_loss = None
        self._allnet_cash_avail = None
        self._allmargn_blocked = None
        self._allutilized_margin = None
        self._allcm_mrgn_cnc_prsnt = None
        self._alltender_mrgn_prsnt = None
        self._allnotnal_cash = None
        self._allscrp_bskt_mrgn = None
        self._allgrosscoltrl = None
        self._allun_real_m2_m_loss = None
        self._allgross_exp = None
        self._allval_delry = None
        self._allunrealized_pnl = None
        self._alladd_mrgn_prsnt = None
        self._allbo_mrgn_reqd = None
        self._allcm_mrgn_mis_prct = None
        self._allmultiplier = None
        self._allcredits = None
        self._allunreal_mtm = None
        self._allpayin = None
        self._allnfo_sprd_benefit = None
        self._allcash_bal = None
        self._allremarks_amnt = None
        self._allcur_spn_mrg_nrml_prsnt = None
        self._allunbook_pnl = None
        self._allcnc_brk_prst = None
        self._allun_real_loss = None
        self._allcur_exp_mrg_mis_prsnt = None
        self._allfo_exp_mrgn_mis_prsnt = None
        self._allbuy_exp = None
        self._allcdssprd_benefits = None
        self._all_un_setld_credit = None
        self._allspan_mrgn_nrml = None
        self._allreal_pnl = None
        self._allspan_mrgn_mis = None
        self._allbrnch_adhoc = None
        self._allipo_amt = None
        self._alladhoc = None
        self._allturnover = None
        self._allreal_mtm = None
        self._allcur_exp_mrg_nrml_prsnt = None
        self._allspan_margn = None
        self._allreal_m2_m_loss = None
        self.discriminator = None
        if allbrokerage_prsnt is not None:
            self.allbrokerage_prsnt = allbrokerage_prsnt
        if allco_mrgn_reqd is not None:
            self.allco_mrgn_reqd = allco_mrgn_reqd
        if allmf_amt is not None:
            self.allmf_amt = allmf_amt
        if allvar_margn is not None:
            self.allvar_margn = allvar_margn
        if allcollateral_val is not None:
            self.allcollateral_val = allcollateral_val
        if allrealized_pnl is not None:
            self.allrealized_pnl = allrealized_pnl
        if allelm_margn is not None:
            self.allelm_margn = allelm_margn
        if allloss_limit is not None:
            self.allloss_limit = allloss_limit
        if allcnc_real_mtm is not None:
            self.allcnc_real_mtm = allcnc_real_mtm
        if allcnc_elmr_margn is not None:
            self.allcnc_elmr_margn = allcnc_elmr_margn
        if allbooked_pnl is not None:
            self.allbooked_pnl = allbooked_pnl
        if allexp_margn is not None:
            self.allexp_margn = allexp_margn
        if allttl_cash_bal is not None:
            self.allttl_cash_bal = allttl_cash_bal
        if allcnc_un_real_mtm is not None:
            self.allcnc_un_real_mtm = allcnc_un_real_mtm
        if allremarks is not None:
            self.allremarks = allremarks
        if allstock_cfs is not None:
            self.allstock_cfs = allstock_cfs
        if allcnc_mrgn_used is not None:
            self.allcnc_mrgn_used = allcnc_mrgn_used
        if allbuypwr is not None:
            self.allbuypwr = allbuypwr
        if all_fd is not None:
            self.all_fd = all_fd
        if allcnc_var_margn is not None:
            self.allcnc_var_margn = allcnc_var_margn
        if allpremium_prsnt is not None:
            self.allpremium_prsnt = allpremium_prsnt
        if alldebits is not None:
            self.alldebits = alldebits
        if allcategory is not None:
            self.allcategory = allcategory
        if alldirct_colatrl is not None:
            self.alldirct_colatrl = alldirct_colatrl
        if allmargn_used is not None:
            self.allmargn_used = allmargn_used
        if all_view_unreal_mtm is not None:
            self.all_view_unreal_mtm = all_view_unreal_mtm
        if allt1_gross_collatrl is not None:
            self.allt1_gross_collatrl = allt1_gross_collatrl
        if allcnc_credit is not None:
            self.allcnc_credit = allcnc_credit
        if allmfss_amnt_used is not None:
            self.allmfss_amnt_used = allmfss_amnt_used
        if allsegment is not None:
            self.allsegment = allsegment
        if alladhoc_margn is not None:
            self.alladhoc_margn = alladhoc_margn
        if alldelivry_mrgn is not None:
            self.alldelivry_mrgn = alldelivry_mrgn
        if alllien is not None:
            self.alllien = alllien
        if allmrgn_srp_bsk_prsnt is not None:
            self.allmrgn_srp_bsk_prsnt = allmrgn_srp_bsk_prsnt
        if allsell_exp is not None:
            self.allsell_exp = allsell_exp
        if alladd_pre_exp_mrgn_prsnt is not None:
            self.alladd_pre_exp_mrgn_prsnt = alladd_pre_exp_mrgn_prsnt
        if alltotal_collateral_val is not None:
            self.alltotal_collateral_val = alltotal_collateral_val
        if alladhoc_srp_mrgn is not None:
            self.alladhoc_srp_mrgn = alladhoc_srp_mrgn
        if allfo_exp_mgn_nrml_prsnt is not None:
            self.allfo_exp_mgn_nrml_prsnt = allfo_exp_mgn_nrml_prsnt
        if allpayout is not None:
            self.allpayout = allpayout
        if allreal_loss is not None:
            self.allreal_loss = allreal_loss
        if allnet_cash_avail is not None:
            self.allnet_cash_avail = allnet_cash_avail
        if allmargn_blocked is not None:
            self.allmargn_blocked = allmargn_blocked
        if allutilized_margin is not None:
            self.allutilized_margin = allutilized_margin
        if allcm_mrgn_cnc_prsnt is not None:
            self.allcm_mrgn_cnc_prsnt = allcm_mrgn_cnc_prsnt
        if alltender_mrgn_prsnt is not None:
            self.alltender_mrgn_prsnt = alltender_mrgn_prsnt
        if allnotnal_cash is not None:
            self.allnotnal_cash = allnotnal_cash
        if allscrp_bskt_mrgn is not None:
            self.allscrp_bskt_mrgn = allscrp_bskt_mrgn
        if allgrosscoltrl is not None:
            self.allgrosscoltrl = allgrosscoltrl
        if allun_real_m2_m_loss is not None:
            self.allun_real_m2_m_loss = allun_real_m2_m_loss
        if allgross_exp is not None:
            self.allgross_exp = allgross_exp
        if allval_delry is not None:
            self.allval_delry = allval_delry
        if allunrealized_pnl is not None:
            self.allunrealized_pnl = allunrealized_pnl
        if alladd_mrgn_prsnt is not None:
            self.alladd_mrgn_prsnt = alladd_mrgn_prsnt
        if allbo_mrgn_reqd is not None:
            self.allbo_mrgn_reqd = allbo_mrgn_reqd
        if allcm_mrgn_mis_prct is not None:
            self.allcm_mrgn_mis_prct = allcm_mrgn_mis_prct
        if allmultiplier is not None:
            self.allmultiplier = allmultiplier
        if allcredits is not None:
            self.allcredits = allcredits
        if allunreal_mtm is not None:
            self.allunreal_mtm = allunreal_mtm
        if allpayin is not None:
            self.allpayin = allpayin
        if allnfo_sprd_benefit is not None:
            self.allnfo_sprd_benefit = allnfo_sprd_benefit
        if allcash_bal is not None:
            self.allcash_bal = allcash_bal
        if allremarks_amnt is not None:
            self.allremarks_amnt = allremarks_amnt
        if allcur_spn_mrg_nrml_prsnt is not None:
            self.allcur_spn_mrg_nrml_prsnt = allcur_spn_mrg_nrml_prsnt
        if allunbook_pnl is not None:
            self.allunbook_pnl = allunbook_pnl
        if allcnc_brk_prst is not None:
            self.allcnc_brk_prst = allcnc_brk_prst
        if allun_real_loss is not None:
            self.allun_real_loss = allun_real_loss
        if allcur_exp_mrg_mis_prsnt is not None:
            self.allcur_exp_mrg_mis_prsnt = allcur_exp_mrg_mis_prsnt
        if allfo_exp_mrgn_mis_prsnt is not None:
            self.allfo_exp_mrgn_mis_prsnt = allfo_exp_mrgn_mis_prsnt
        if allbuy_exp is not None:
            self.allbuy_exp = allbuy_exp
        if allcdssprd_benefits is not None:
            self.allcdssprd_benefits = allcdssprd_benefits
        if all_un_setld_credit is not None:
            self.all_un_setld_credit = all_un_setld_credit
        if allspan_mrgn_nrml is not None:
            self.allspan_mrgn_nrml = allspan_mrgn_nrml
        if allreal_pnl is not None:
            self.allreal_pnl = allreal_pnl
        if allspan_mrgn_mis is not None:
            self.allspan_mrgn_mis = allspan_mrgn_mis
        if allbrnch_adhoc is not None:
            self.allbrnch_adhoc = allbrnch_adhoc
        if allipo_amt is not None:
            self.allipo_amt = allipo_amt
        if alladhoc is not None:
            self.alladhoc = alladhoc
        if allturnover is not None:
            self.allturnover = allturnover
        if allreal_mtm is not None:
            self.allreal_mtm = allreal_mtm
        if allcur_exp_mrg_nrml_prsnt is not None:
            self.allcur_exp_mrg_nrml_prsnt = allcur_exp_mrg_nrml_prsnt
        if allspan_margn is not None:
            self.allspan_margn = allspan_margn
        if allreal_m2_m_loss is not None:
            self.allreal_m2_m_loss = allreal_m2_m_loss

    @property
    def allbrokerage_prsnt(self):
        """Gets the allbrokerage_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allbrokerage_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allbrokerage_prsnt

    @allbrokerage_prsnt.setter
    def allbrokerage_prsnt(self, allbrokerage_prsnt):
        """Sets the allbrokerage_prsnt of this FundsSucessDataALL.


        :param allbrokerage_prsnt: The allbrokerage_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allbrokerage_prsnt = allbrokerage_prsnt

    @property
    def allco_mrgn_reqd(self):
        """Gets the allco_mrgn_reqd of this FundsSucessDataALL.  # noqa: E501


        :return: The allco_mrgn_reqd of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allco_mrgn_reqd

    @allco_mrgn_reqd.setter
    def allco_mrgn_reqd(self, allco_mrgn_reqd):
        """Sets the allco_mrgn_reqd of this FundsSucessDataALL.


        :param allco_mrgn_reqd: The allco_mrgn_reqd of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allco_mrgn_reqd = allco_mrgn_reqd

    @property
    def allmf_amt(self):
        """Gets the allmf_amt of this FundsSucessDataALL.  # noqa: E501


        :return: The allmf_amt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allmf_amt

    @allmf_amt.setter
    def allmf_amt(self, allmf_amt):
        """Sets the allmf_amt of this FundsSucessDataALL.


        :param allmf_amt: The allmf_amt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allmf_amt = allmf_amt

    @property
    def allvar_margn(self):
        """Gets the allvar_margn of this FundsSucessDataALL.  # noqa: E501


        :return: The allvar_margn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allvar_margn

    @allvar_margn.setter
    def allvar_margn(self, allvar_margn):
        """Sets the allvar_margn of this FundsSucessDataALL.


        :param allvar_margn: The allvar_margn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allvar_margn = allvar_margn

    @property
    def allcollateral_val(self):
        """Gets the allcollateral_val of this FundsSucessDataALL.  # noqa: E501


        :return: The allcollateral_val of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcollateral_val

    @allcollateral_val.setter
    def allcollateral_val(self, allcollateral_val):
        """Sets the allcollateral_val of this FundsSucessDataALL.


        :param allcollateral_val: The allcollateral_val of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcollateral_val = allcollateral_val

    @property
    def allrealized_pnl(self):
        """Gets the allrealized_pnl of this FundsSucessDataALL.  # noqa: E501


        :return: The allrealized_pnl of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allrealized_pnl

    @allrealized_pnl.setter
    def allrealized_pnl(self, allrealized_pnl):
        """Sets the allrealized_pnl of this FundsSucessDataALL.


        :param allrealized_pnl: The allrealized_pnl of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allrealized_pnl = allrealized_pnl

    @property
    def allelm_margn(self):
        """Gets the allelm_margn of this FundsSucessDataALL.  # noqa: E501


        :return: The allelm_margn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allelm_margn

    @allelm_margn.setter
    def allelm_margn(self, allelm_margn):
        """Sets the allelm_margn of this FundsSucessDataALL.


        :param allelm_margn: The allelm_margn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allelm_margn = allelm_margn

    @property
    def allloss_limit(self):
        """Gets the allloss_limit of this FundsSucessDataALL.  # noqa: E501


        :return: The allloss_limit of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allloss_limit

    @allloss_limit.setter
    def allloss_limit(self, allloss_limit):
        """Sets the allloss_limit of this FundsSucessDataALL.


        :param allloss_limit: The allloss_limit of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allloss_limit = allloss_limit

    @property
    def allcnc_real_mtm(self):
        """Gets the allcnc_real_mtm of this FundsSucessDataALL.  # noqa: E501


        :return: The allcnc_real_mtm of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcnc_real_mtm

    @allcnc_real_mtm.setter
    def allcnc_real_mtm(self, allcnc_real_mtm):
        """Sets the allcnc_real_mtm of this FundsSucessDataALL.


        :param allcnc_real_mtm: The allcnc_real_mtm of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcnc_real_mtm = allcnc_real_mtm

    @property
    def allcnc_elmr_margn(self):
        """Gets the allcnc_elmr_margn of this FundsSucessDataALL.  # noqa: E501


        :return: The allcnc_elmr_margn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcnc_elmr_margn

    @allcnc_elmr_margn.setter
    def allcnc_elmr_margn(self, allcnc_elmr_margn):
        """Sets the allcnc_elmr_margn of this FundsSucessDataALL.


        :param allcnc_elmr_margn: The allcnc_elmr_margn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcnc_elmr_margn = allcnc_elmr_margn

    @property
    def allbooked_pnl(self):
        """Gets the allbooked_pnl of this FundsSucessDataALL.  # noqa: E501


        :return: The allbooked_pnl of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allbooked_pnl

    @allbooked_pnl.setter
    def allbooked_pnl(self, allbooked_pnl):
        """Sets the allbooked_pnl of this FundsSucessDataALL.


        :param allbooked_pnl: The allbooked_pnl of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allbooked_pnl = allbooked_pnl

    @property
    def allexp_margn(self):
        """Gets the allexp_margn of this FundsSucessDataALL.  # noqa: E501


        :return: The allexp_margn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allexp_margn

    @allexp_margn.setter
    def allexp_margn(self, allexp_margn):
        """Sets the allexp_margn of this FundsSucessDataALL.


        :param allexp_margn: The allexp_margn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allexp_margn = allexp_margn

    @property
    def allttl_cash_bal(self):
        """Gets the allttl_cash_bal of this FundsSucessDataALL.  # noqa: E501


        :return: The allttl_cash_bal of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allttl_cash_bal

    @allttl_cash_bal.setter
    def allttl_cash_bal(self, allttl_cash_bal):
        """Sets the allttl_cash_bal of this FundsSucessDataALL.


        :param allttl_cash_bal: The allttl_cash_bal of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allttl_cash_bal = allttl_cash_bal

    @property
    def allcnc_un_real_mtm(self):
        """Gets the allcnc_un_real_mtm of this FundsSucessDataALL.  # noqa: E501


        :return: The allcnc_un_real_mtm of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcnc_un_real_mtm

    @allcnc_un_real_mtm.setter
    def allcnc_un_real_mtm(self, allcnc_un_real_mtm):
        """Sets the allcnc_un_real_mtm of this FundsSucessDataALL.


        :param allcnc_un_real_mtm: The allcnc_un_real_mtm of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcnc_un_real_mtm = allcnc_un_real_mtm

    @property
    def allremarks(self):
        """Gets the allremarks of this FundsSucessDataALL.  # noqa: E501


        :return: The allremarks of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allremarks

    @allremarks.setter
    def allremarks(self, allremarks):
        """Sets the allremarks of this FundsSucessDataALL.


        :param allremarks: The allremarks of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allremarks = allremarks

    @property
    def allstock_cfs(self):
        """Gets the allstock_cfs of this FundsSucessDataALL.  # noqa: E501


        :return: The allstock_cfs of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allstock_cfs

    @allstock_cfs.setter
    def allstock_cfs(self, allstock_cfs):
        """Sets the allstock_cfs of this FundsSucessDataALL.


        :param allstock_cfs: The allstock_cfs of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allstock_cfs = allstock_cfs

    @property
    def allcnc_mrgn_used(self):
        """Gets the allcnc_mrgn_used of this FundsSucessDataALL.  # noqa: E501


        :return: The allcnc_mrgn_used of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcnc_mrgn_used

    @allcnc_mrgn_used.setter
    def allcnc_mrgn_used(self, allcnc_mrgn_used):
        """Sets the allcnc_mrgn_used of this FundsSucessDataALL.


        :param allcnc_mrgn_used: The allcnc_mrgn_used of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcnc_mrgn_used = allcnc_mrgn_used

    @property
    def allbuypwr(self):
        """Gets the allbuypwr of this FundsSucessDataALL.  # noqa: E501


        :return: The allbuypwr of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allbuypwr

    @allbuypwr.setter
    def allbuypwr(self, allbuypwr):
        """Sets the allbuypwr of this FundsSucessDataALL.


        :param allbuypwr: The allbuypwr of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allbuypwr = allbuypwr

    @property
    def all_fd(self):
        """Gets the all_fd of this FundsSucessDataALL.  # noqa: E501


        :return: The all_fd of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._all_fd

    @all_fd.setter
    def all_fd(self, all_fd):
        """Sets the all_fd of this FundsSucessDataALL.


        :param all_fd: The all_fd of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._all_fd = all_fd

    @property
    def allcnc_var_margn(self):
        """Gets the allcnc_var_margn of this FundsSucessDataALL.  # noqa: E501


        :return: The allcnc_var_margn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcnc_var_margn

    @allcnc_var_margn.setter
    def allcnc_var_margn(self, allcnc_var_margn):
        """Sets the allcnc_var_margn of this FundsSucessDataALL.


        :param allcnc_var_margn: The allcnc_var_margn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcnc_var_margn = allcnc_var_margn

    @property
    def allpremium_prsnt(self):
        """Gets the allpremium_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allpremium_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allpremium_prsnt

    @allpremium_prsnt.setter
    def allpremium_prsnt(self, allpremium_prsnt):
        """Sets the allpremium_prsnt of this FundsSucessDataALL.


        :param allpremium_prsnt: The allpremium_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allpremium_prsnt = allpremium_prsnt

    @property
    def alldebits(self):
        """Gets the alldebits of this FundsSucessDataALL.  # noqa: E501


        :return: The alldebits of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alldebits

    @alldebits.setter
    def alldebits(self, alldebits):
        """Sets the alldebits of this FundsSucessDataALL.


        :param alldebits: The alldebits of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alldebits = alldebits

    @property
    def allcategory(self):
        """Gets the allcategory of this FundsSucessDataALL.  # noqa: E501


        :return: The allcategory of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcategory

    @allcategory.setter
    def allcategory(self, allcategory):
        """Sets the allcategory of this FundsSucessDataALL.


        :param allcategory: The allcategory of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcategory = allcategory

    @property
    def alldirct_colatrl(self):
        """Gets the alldirct_colatrl of this FundsSucessDataALL.  # noqa: E501


        :return: The alldirct_colatrl of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alldirct_colatrl

    @alldirct_colatrl.setter
    def alldirct_colatrl(self, alldirct_colatrl):
        """Sets the alldirct_colatrl of this FundsSucessDataALL.


        :param alldirct_colatrl: The alldirct_colatrl of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alldirct_colatrl = alldirct_colatrl

    @property
    def allmargn_used(self):
        """Gets the allmargn_used of this FundsSucessDataALL.  # noqa: E501


        :return: The allmargn_used of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allmargn_used

    @allmargn_used.setter
    def allmargn_used(self, allmargn_used):
        """Sets the allmargn_used of this FundsSucessDataALL.


        :param allmargn_used: The allmargn_used of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allmargn_used = allmargn_used

    @property
    def all_view_unreal_mtm(self):
        """Gets the all_view_unreal_mtm of this FundsSucessDataALL.  # noqa: E501


        :return: The all_view_unreal_mtm of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._all_view_unreal_mtm

    @all_view_unreal_mtm.setter
    def all_view_unreal_mtm(self, all_view_unreal_mtm):
        """Sets the all_view_unreal_mtm of this FundsSucessDataALL.


        :param all_view_unreal_mtm: The all_view_unreal_mtm of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._all_view_unreal_mtm = all_view_unreal_mtm

    @property
    def allt1_gross_collatrl(self):
        """Gets the allt1_gross_collatrl of this FundsSucessDataALL.  # noqa: E501


        :return: The allt1_gross_collatrl of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allt1_gross_collatrl

    @allt1_gross_collatrl.setter
    def allt1_gross_collatrl(self, allt1_gross_collatrl):
        """Sets the allt1_gross_collatrl of this FundsSucessDataALL.


        :param allt1_gross_collatrl: The allt1_gross_collatrl of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allt1_gross_collatrl = allt1_gross_collatrl

    @property
    def allcnc_credit(self):
        """Gets the allcnc_credit of this FundsSucessDataALL.  # noqa: E501


        :return: The allcnc_credit of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcnc_credit

    @allcnc_credit.setter
    def allcnc_credit(self, allcnc_credit):
        """Sets the allcnc_credit of this FundsSucessDataALL.


        :param allcnc_credit: The allcnc_credit of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcnc_credit = allcnc_credit

    @property
    def allmfss_amnt_used(self):
        """Gets the allmfss_amnt_used of this FundsSucessDataALL.  # noqa: E501


        :return: The allmfss_amnt_used of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allmfss_amnt_used

    @allmfss_amnt_used.setter
    def allmfss_amnt_used(self, allmfss_amnt_used):
        """Sets the allmfss_amnt_used of this FundsSucessDataALL.


        :param allmfss_amnt_used: The allmfss_amnt_used of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allmfss_amnt_used = allmfss_amnt_used

    @property
    def allsegment(self):
        """Gets the allsegment of this FundsSucessDataALL.  # noqa: E501


        :return: The allsegment of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allsegment

    @allsegment.setter
    def allsegment(self, allsegment):
        """Sets the allsegment of this FundsSucessDataALL.


        :param allsegment: The allsegment of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allsegment = allsegment

    @property
    def alladhoc_margn(self):
        """Gets the alladhoc_margn of this FundsSucessDataALL.  # noqa: E501


        :return: The alladhoc_margn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alladhoc_margn

    @alladhoc_margn.setter
    def alladhoc_margn(self, alladhoc_margn):
        """Sets the alladhoc_margn of this FundsSucessDataALL.


        :param alladhoc_margn: The alladhoc_margn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alladhoc_margn = alladhoc_margn

    @property
    def alldelivry_mrgn(self):
        """Gets the alldelivry_mrgn of this FundsSucessDataALL.  # noqa: E501


        :return: The alldelivry_mrgn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alldelivry_mrgn

    @alldelivry_mrgn.setter
    def alldelivry_mrgn(self, alldelivry_mrgn):
        """Sets the alldelivry_mrgn of this FundsSucessDataALL.


        :param alldelivry_mrgn: The alldelivry_mrgn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alldelivry_mrgn = alldelivry_mrgn

    @property
    def alllien(self):
        """Gets the alllien of this FundsSucessDataALL.  # noqa: E501


        :return: The alllien of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alllien

    @alllien.setter
    def alllien(self, alllien):
        """Sets the alllien of this FundsSucessDataALL.


        :param alllien: The alllien of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alllien = alllien

    @property
    def allmrgn_srp_bsk_prsnt(self):
        """Gets the allmrgn_srp_bsk_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allmrgn_srp_bsk_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allmrgn_srp_bsk_prsnt

    @allmrgn_srp_bsk_prsnt.setter
    def allmrgn_srp_bsk_prsnt(self, allmrgn_srp_bsk_prsnt):
        """Sets the allmrgn_srp_bsk_prsnt of this FundsSucessDataALL.


        :param allmrgn_srp_bsk_prsnt: The allmrgn_srp_bsk_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allmrgn_srp_bsk_prsnt = allmrgn_srp_bsk_prsnt

    @property
    def allsell_exp(self):
        """Gets the allsell_exp of this FundsSucessDataALL.  # noqa: E501


        :return: The allsell_exp of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allsell_exp

    @allsell_exp.setter
    def allsell_exp(self, allsell_exp):
        """Sets the allsell_exp of this FundsSucessDataALL.


        :param allsell_exp: The allsell_exp of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allsell_exp = allsell_exp

    @property
    def alladd_pre_exp_mrgn_prsnt(self):
        """Gets the alladd_pre_exp_mrgn_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The alladd_pre_exp_mrgn_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alladd_pre_exp_mrgn_prsnt

    @alladd_pre_exp_mrgn_prsnt.setter
    def alladd_pre_exp_mrgn_prsnt(self, alladd_pre_exp_mrgn_prsnt):
        """Sets the alladd_pre_exp_mrgn_prsnt of this FundsSucessDataALL.


        :param alladd_pre_exp_mrgn_prsnt: The alladd_pre_exp_mrgn_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alladd_pre_exp_mrgn_prsnt = alladd_pre_exp_mrgn_prsnt

    @property
    def alltotal_collateral_val(self):
        """Gets the alltotal_collateral_val of this FundsSucessDataALL.  # noqa: E501


        :return: The alltotal_collateral_val of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alltotal_collateral_val

    @alltotal_collateral_val.setter
    def alltotal_collateral_val(self, alltotal_collateral_val):
        """Sets the alltotal_collateral_val of this FundsSucessDataALL.


        :param alltotal_collateral_val: The alltotal_collateral_val of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alltotal_collateral_val = alltotal_collateral_val

    @property
    def alladhoc_srp_mrgn(self):
        """Gets the alladhoc_srp_mrgn of this FundsSucessDataALL.  # noqa: E501


        :return: The alladhoc_srp_mrgn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alladhoc_srp_mrgn

    @alladhoc_srp_mrgn.setter
    def alladhoc_srp_mrgn(self, alladhoc_srp_mrgn):
        """Sets the alladhoc_srp_mrgn of this FundsSucessDataALL.


        :param alladhoc_srp_mrgn: The alladhoc_srp_mrgn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alladhoc_srp_mrgn = alladhoc_srp_mrgn

    @property
    def allfo_exp_mgn_nrml_prsnt(self):
        """Gets the allfo_exp_mgn_nrml_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allfo_exp_mgn_nrml_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allfo_exp_mgn_nrml_prsnt

    @allfo_exp_mgn_nrml_prsnt.setter
    def allfo_exp_mgn_nrml_prsnt(self, allfo_exp_mgn_nrml_prsnt):
        """Sets the allfo_exp_mgn_nrml_prsnt of this FundsSucessDataALL.


        :param allfo_exp_mgn_nrml_prsnt: The allfo_exp_mgn_nrml_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allfo_exp_mgn_nrml_prsnt = allfo_exp_mgn_nrml_prsnt

    @property
    def allpayout(self):
        """Gets the allpayout of this FundsSucessDataALL.  # noqa: E501


        :return: The allpayout of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allpayout

    @allpayout.setter
    def allpayout(self, allpayout):
        """Sets the allpayout of this FundsSucessDataALL.


        :param allpayout: The allpayout of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allpayout = allpayout

    @property
    def allreal_loss(self):
        """Gets the allreal_loss of this FundsSucessDataALL.  # noqa: E501


        :return: The allreal_loss of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allreal_loss

    @allreal_loss.setter
    def allreal_loss(self, allreal_loss):
        """Sets the allreal_loss of this FundsSucessDataALL.


        :param allreal_loss: The allreal_loss of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allreal_loss = allreal_loss

    @property
    def allnet_cash_avail(self):
        """Gets the allnet_cash_avail of this FundsSucessDataALL.  # noqa: E501


        :return: The allnet_cash_avail of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allnet_cash_avail

    @allnet_cash_avail.setter
    def allnet_cash_avail(self, allnet_cash_avail):
        """Sets the allnet_cash_avail of this FundsSucessDataALL.


        :param allnet_cash_avail: The allnet_cash_avail of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allnet_cash_avail = allnet_cash_avail

    @property
    def allmargn_blocked(self):
        """Gets the allmargn_blocked of this FundsSucessDataALL.  # noqa: E501


        :return: The allmargn_blocked of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allmargn_blocked

    @allmargn_blocked.setter
    def allmargn_blocked(self, allmargn_blocked):
        """Sets the allmargn_blocked of this FundsSucessDataALL.


        :param allmargn_blocked: The allmargn_blocked of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allmargn_blocked = allmargn_blocked

    @property
    def allutilized_margin(self):
        """Gets the allutilized_margin of this FundsSucessDataALL.  # noqa: E501


        :return: The allutilized_margin of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allutilized_margin

    @allutilized_margin.setter
    def allutilized_margin(self, allutilized_margin):
        """Sets the allutilized_margin of this FundsSucessDataALL.


        :param allutilized_margin: The allutilized_margin of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allutilized_margin = allutilized_margin

    @property
    def allcm_mrgn_cnc_prsnt(self):
        """Gets the allcm_mrgn_cnc_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allcm_mrgn_cnc_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcm_mrgn_cnc_prsnt

    @allcm_mrgn_cnc_prsnt.setter
    def allcm_mrgn_cnc_prsnt(self, allcm_mrgn_cnc_prsnt):
        """Sets the allcm_mrgn_cnc_prsnt of this FundsSucessDataALL.


        :param allcm_mrgn_cnc_prsnt: The allcm_mrgn_cnc_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcm_mrgn_cnc_prsnt = allcm_mrgn_cnc_prsnt

    @property
    def alltender_mrgn_prsnt(self):
        """Gets the alltender_mrgn_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The alltender_mrgn_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alltender_mrgn_prsnt

    @alltender_mrgn_prsnt.setter
    def alltender_mrgn_prsnt(self, alltender_mrgn_prsnt):
        """Sets the alltender_mrgn_prsnt of this FundsSucessDataALL.


        :param alltender_mrgn_prsnt: The alltender_mrgn_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alltender_mrgn_prsnt = alltender_mrgn_prsnt

    @property
    def allnotnal_cash(self):
        """Gets the allnotnal_cash of this FundsSucessDataALL.  # noqa: E501


        :return: The allnotnal_cash of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allnotnal_cash

    @allnotnal_cash.setter
    def allnotnal_cash(self, allnotnal_cash):
        """Sets the allnotnal_cash of this FundsSucessDataALL.


        :param allnotnal_cash: The allnotnal_cash of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allnotnal_cash = allnotnal_cash

    @property
    def allscrp_bskt_mrgn(self):
        """Gets the allscrp_bskt_mrgn of this FundsSucessDataALL.  # noqa: E501


        :return: The allscrp_bskt_mrgn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allscrp_bskt_mrgn

    @allscrp_bskt_mrgn.setter
    def allscrp_bskt_mrgn(self, allscrp_bskt_mrgn):
        """Sets the allscrp_bskt_mrgn of this FundsSucessDataALL.


        :param allscrp_bskt_mrgn: The allscrp_bskt_mrgn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allscrp_bskt_mrgn = allscrp_bskt_mrgn

    @property
    def allgrosscoltrl(self):
        """Gets the allgrosscoltrl of this FundsSucessDataALL.  # noqa: E501


        :return: The allgrosscoltrl of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allgrosscoltrl

    @allgrosscoltrl.setter
    def allgrosscoltrl(self, allgrosscoltrl):
        """Sets the allgrosscoltrl of this FundsSucessDataALL.


        :param allgrosscoltrl: The allgrosscoltrl of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allgrosscoltrl = allgrosscoltrl

    @property
    def allun_real_m2_m_loss(self):
        """Gets the allun_real_m2_m_loss of this FundsSucessDataALL.  # noqa: E501


        :return: The allun_real_m2_m_loss of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allun_real_m2_m_loss

    @allun_real_m2_m_loss.setter
    def allun_real_m2_m_loss(self, allun_real_m2_m_loss):
        """Sets the allun_real_m2_m_loss of this FundsSucessDataALL.


        :param allun_real_m2_m_loss: The allun_real_m2_m_loss of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allun_real_m2_m_loss = allun_real_m2_m_loss

    @property
    def allgross_exp(self):
        """Gets the allgross_exp of this FundsSucessDataALL.  # noqa: E501


        :return: The allgross_exp of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allgross_exp

    @allgross_exp.setter
    def allgross_exp(self, allgross_exp):
        """Sets the allgross_exp of this FundsSucessDataALL.


        :param allgross_exp: The allgross_exp of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allgross_exp = allgross_exp

    @property
    def allval_delry(self):
        """Gets the allval_delry of this FundsSucessDataALL.  # noqa: E501


        :return: The allval_delry of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allval_delry

    @allval_delry.setter
    def allval_delry(self, allval_delry):
        """Sets the allval_delry of this FundsSucessDataALL.


        :param allval_delry: The allval_delry of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allval_delry = allval_delry

    @property
    def allunrealized_pnl(self):
        """Gets the allunrealized_pnl of this FundsSucessDataALL.  # noqa: E501


        :return: The allunrealized_pnl of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allunrealized_pnl

    @allunrealized_pnl.setter
    def allunrealized_pnl(self, allunrealized_pnl):
        """Sets the allunrealized_pnl of this FundsSucessDataALL.


        :param allunrealized_pnl: The allunrealized_pnl of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allunrealized_pnl = allunrealized_pnl

    @property
    def alladd_mrgn_prsnt(self):
        """Gets the alladd_mrgn_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The alladd_mrgn_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alladd_mrgn_prsnt

    @alladd_mrgn_prsnt.setter
    def alladd_mrgn_prsnt(self, alladd_mrgn_prsnt):
        """Sets the alladd_mrgn_prsnt of this FundsSucessDataALL.


        :param alladd_mrgn_prsnt: The alladd_mrgn_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alladd_mrgn_prsnt = alladd_mrgn_prsnt

    @property
    def allbo_mrgn_reqd(self):
        """Gets the allbo_mrgn_reqd of this FundsSucessDataALL.  # noqa: E501


        :return: The allbo_mrgn_reqd of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allbo_mrgn_reqd

    @allbo_mrgn_reqd.setter
    def allbo_mrgn_reqd(self, allbo_mrgn_reqd):
        """Sets the allbo_mrgn_reqd of this FundsSucessDataALL.


        :param allbo_mrgn_reqd: The allbo_mrgn_reqd of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allbo_mrgn_reqd = allbo_mrgn_reqd

    @property
    def allcm_mrgn_mis_prct(self):
        """Gets the allcm_mrgn_mis_prct of this FundsSucessDataALL.  # noqa: E501


        :return: The allcm_mrgn_mis_prct of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcm_mrgn_mis_prct

    @allcm_mrgn_mis_prct.setter
    def allcm_mrgn_mis_prct(self, allcm_mrgn_mis_prct):
        """Sets the allcm_mrgn_mis_prct of this FundsSucessDataALL.


        :param allcm_mrgn_mis_prct: The allcm_mrgn_mis_prct of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcm_mrgn_mis_prct = allcm_mrgn_mis_prct

    @property
    def allmultiplier(self):
        """Gets the allmultiplier of this FundsSucessDataALL.  # noqa: E501


        :return: The allmultiplier of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allmultiplier

    @allmultiplier.setter
    def allmultiplier(self, allmultiplier):
        """Sets the allmultiplier of this FundsSucessDataALL.


        :param allmultiplier: The allmultiplier of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allmultiplier = allmultiplier

    @property
    def allcredits(self):
        """Gets the allcredits of this FundsSucessDataALL.  # noqa: E501


        :return: The allcredits of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcredits

    @allcredits.setter
    def allcredits(self, allcredits):
        """Sets the allcredits of this FundsSucessDataALL.


        :param allcredits: The allcredits of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcredits = allcredits

    @property
    def allunreal_mtm(self):
        """Gets the allunreal_mtm of this FundsSucessDataALL.  # noqa: E501


        :return: The allunreal_mtm of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allunreal_mtm

    @allunreal_mtm.setter
    def allunreal_mtm(self, allunreal_mtm):
        """Sets the allunreal_mtm of this FundsSucessDataALL.


        :param allunreal_mtm: The allunreal_mtm of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allunreal_mtm = allunreal_mtm

    @property
    def allpayin(self):
        """Gets the allpayin of this FundsSucessDataALL.  # noqa: E501


        :return: The allpayin of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allpayin

    @allpayin.setter
    def allpayin(self, allpayin):
        """Sets the allpayin of this FundsSucessDataALL.


        :param allpayin: The allpayin of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allpayin = allpayin

    @property
    def allnfo_sprd_benefit(self):
        """Gets the allnfo_sprd_benefit of this FundsSucessDataALL.  # noqa: E501


        :return: The allnfo_sprd_benefit of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allnfo_sprd_benefit

    @allnfo_sprd_benefit.setter
    def allnfo_sprd_benefit(self, allnfo_sprd_benefit):
        """Sets the allnfo_sprd_benefit of this FundsSucessDataALL.


        :param allnfo_sprd_benefit: The allnfo_sprd_benefit of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allnfo_sprd_benefit = allnfo_sprd_benefit

    @property
    def allcash_bal(self):
        """Gets the allcash_bal of this FundsSucessDataALL.  # noqa: E501


        :return: The allcash_bal of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcash_bal

    @allcash_bal.setter
    def allcash_bal(self, allcash_bal):
        """Sets the allcash_bal of this FundsSucessDataALL.


        :param allcash_bal: The allcash_bal of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcash_bal = allcash_bal

    @property
    def allremarks_amnt(self):
        """Gets the allremarks_amnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allremarks_amnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allremarks_amnt

    @allremarks_amnt.setter
    def allremarks_amnt(self, allremarks_amnt):
        """Sets the allremarks_amnt of this FundsSucessDataALL.


        :param allremarks_amnt: The allremarks_amnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allremarks_amnt = allremarks_amnt

    @property
    def allcur_spn_mrg_nrml_prsnt(self):
        """Gets the allcur_spn_mrg_nrml_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allcur_spn_mrg_nrml_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcur_spn_mrg_nrml_prsnt

    @allcur_spn_mrg_nrml_prsnt.setter
    def allcur_spn_mrg_nrml_prsnt(self, allcur_spn_mrg_nrml_prsnt):
        """Sets the allcur_spn_mrg_nrml_prsnt of this FundsSucessDataALL.


        :param allcur_spn_mrg_nrml_prsnt: The allcur_spn_mrg_nrml_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcur_spn_mrg_nrml_prsnt = allcur_spn_mrg_nrml_prsnt

    @property
    def allunbook_pnl(self):
        """Gets the allunbook_pnl of this FundsSucessDataALL.  # noqa: E501


        :return: The allunbook_pnl of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allunbook_pnl

    @allunbook_pnl.setter
    def allunbook_pnl(self, allunbook_pnl):
        """Sets the allunbook_pnl of this FundsSucessDataALL.


        :param allunbook_pnl: The allunbook_pnl of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allunbook_pnl = allunbook_pnl

    @property
    def allcnc_brk_prst(self):
        """Gets the allcnc_brk_prst of this FundsSucessDataALL.  # noqa: E501


        :return: The allcnc_brk_prst of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcnc_brk_prst

    @allcnc_brk_prst.setter
    def allcnc_brk_prst(self, allcnc_brk_prst):
        """Sets the allcnc_brk_prst of this FundsSucessDataALL.


        :param allcnc_brk_prst: The allcnc_brk_prst of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcnc_brk_prst = allcnc_brk_prst

    @property
    def allun_real_loss(self):
        """Gets the allun_real_loss of this FundsSucessDataALL.  # noqa: E501


        :return: The allun_real_loss of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allun_real_loss

    @allun_real_loss.setter
    def allun_real_loss(self, allun_real_loss):
        """Sets the allun_real_loss of this FundsSucessDataALL.


        :param allun_real_loss: The allun_real_loss of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allun_real_loss = allun_real_loss

    @property
    def allcur_exp_mrg_mis_prsnt(self):
        """Gets the allcur_exp_mrg_mis_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allcur_exp_mrg_mis_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcur_exp_mrg_mis_prsnt

    @allcur_exp_mrg_mis_prsnt.setter
    def allcur_exp_mrg_mis_prsnt(self, allcur_exp_mrg_mis_prsnt):
        """Sets the allcur_exp_mrg_mis_prsnt of this FundsSucessDataALL.


        :param allcur_exp_mrg_mis_prsnt: The allcur_exp_mrg_mis_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcur_exp_mrg_mis_prsnt = allcur_exp_mrg_mis_prsnt

    @property
    def allfo_exp_mrgn_mis_prsnt(self):
        """Gets the allfo_exp_mrgn_mis_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allfo_exp_mrgn_mis_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allfo_exp_mrgn_mis_prsnt

    @allfo_exp_mrgn_mis_prsnt.setter
    def allfo_exp_mrgn_mis_prsnt(self, allfo_exp_mrgn_mis_prsnt):
        """Sets the allfo_exp_mrgn_mis_prsnt of this FundsSucessDataALL.


        :param allfo_exp_mrgn_mis_prsnt: The allfo_exp_mrgn_mis_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allfo_exp_mrgn_mis_prsnt = allfo_exp_mrgn_mis_prsnt

    @property
    def allbuy_exp(self):
        """Gets the allbuy_exp of this FundsSucessDataALL.  # noqa: E501


        :return: The allbuy_exp of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allbuy_exp

    @allbuy_exp.setter
    def allbuy_exp(self, allbuy_exp):
        """Sets the allbuy_exp of this FundsSucessDataALL.


        :param allbuy_exp: The allbuy_exp of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allbuy_exp = allbuy_exp

    @property
    def allcdssprd_benefits(self):
        """Gets the allcdssprd_benefits of this FundsSucessDataALL.  # noqa: E501


        :return: The allcdssprd_benefits of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcdssprd_benefits

    @allcdssprd_benefits.setter
    def allcdssprd_benefits(self, allcdssprd_benefits):
        """Sets the allcdssprd_benefits of this FundsSucessDataALL.


        :param allcdssprd_benefits: The allcdssprd_benefits of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcdssprd_benefits = allcdssprd_benefits

    @property
    def all_un_setld_credit(self):
        """Gets the all_un_setld_credit of this FundsSucessDataALL.  # noqa: E501


        :return: The all_un_setld_credit of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._all_un_setld_credit

    @all_un_setld_credit.setter
    def all_un_setld_credit(self, all_un_setld_credit):
        """Sets the all_un_setld_credit of this FundsSucessDataALL.


        :param all_un_setld_credit: The all_un_setld_credit of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._all_un_setld_credit = all_un_setld_credit

    @property
    def allspan_mrgn_nrml(self):
        """Gets the allspan_mrgn_nrml of this FundsSucessDataALL.  # noqa: E501


        :return: The allspan_mrgn_nrml of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allspan_mrgn_nrml

    @allspan_mrgn_nrml.setter
    def allspan_mrgn_nrml(self, allspan_mrgn_nrml):
        """Sets the allspan_mrgn_nrml of this FundsSucessDataALL.


        :param allspan_mrgn_nrml: The allspan_mrgn_nrml of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allspan_mrgn_nrml = allspan_mrgn_nrml

    @property
    def allreal_pnl(self):
        """Gets the allreal_pnl of this FundsSucessDataALL.  # noqa: E501


        :return: The allreal_pnl of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allreal_pnl

    @allreal_pnl.setter
    def allreal_pnl(self, allreal_pnl):
        """Sets the allreal_pnl of this FundsSucessDataALL.


        :param allreal_pnl: The allreal_pnl of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allreal_pnl = allreal_pnl

    @property
    def allspan_mrgn_mis(self):
        """Gets the allspan_mrgn_mis of this FundsSucessDataALL.  # noqa: E501


        :return: The allspan_mrgn_mis of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allspan_mrgn_mis

    @allspan_mrgn_mis.setter
    def allspan_mrgn_mis(self, allspan_mrgn_mis):
        """Sets the allspan_mrgn_mis of this FundsSucessDataALL.


        :param allspan_mrgn_mis: The allspan_mrgn_mis of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allspan_mrgn_mis = allspan_mrgn_mis

    @property
    def allbrnch_adhoc(self):
        """Gets the allbrnch_adhoc of this FundsSucessDataALL.  # noqa: E501


        :return: The allbrnch_adhoc of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allbrnch_adhoc

    @allbrnch_adhoc.setter
    def allbrnch_adhoc(self, allbrnch_adhoc):
        """Sets the allbrnch_adhoc of this FundsSucessDataALL.


        :param allbrnch_adhoc: The allbrnch_adhoc of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allbrnch_adhoc = allbrnch_adhoc

    @property
    def allipo_amt(self):
        """Gets the allipo_amt of this FundsSucessDataALL.  # noqa: E501


        :return: The allipo_amt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allipo_amt

    @allipo_amt.setter
    def allipo_amt(self, allipo_amt):
        """Sets the allipo_amt of this FundsSucessDataALL.


        :param allipo_amt: The allipo_amt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allipo_amt = allipo_amt

    @property
    def alladhoc(self):
        """Gets the alladhoc of this FundsSucessDataALL.  # noqa: E501


        :return: The alladhoc of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._alladhoc

    @alladhoc.setter
    def alladhoc(self, alladhoc):
        """Sets the alladhoc of this FundsSucessDataALL.


        :param alladhoc: The alladhoc of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._alladhoc = alladhoc

    @property
    def allturnover(self):
        """Gets the allturnover of this FundsSucessDataALL.  # noqa: E501


        :return: The allturnover of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allturnover

    @allturnover.setter
    def allturnover(self, allturnover):
        """Sets the allturnover of this FundsSucessDataALL.


        :param allturnover: The allturnover of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allturnover = allturnover

    @property
    def allreal_mtm(self):
        """Gets the allreal_mtm of this FundsSucessDataALL.  # noqa: E501


        :return: The allreal_mtm of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allreal_mtm

    @allreal_mtm.setter
    def allreal_mtm(self, allreal_mtm):
        """Sets the allreal_mtm of this FundsSucessDataALL.


        :param allreal_mtm: The allreal_mtm of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allreal_mtm = allreal_mtm

    @property
    def allcur_exp_mrg_nrml_prsnt(self):
        """Gets the allcur_exp_mrg_nrml_prsnt of this FundsSucessDataALL.  # noqa: E501


        :return: The allcur_exp_mrg_nrml_prsnt of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allcur_exp_mrg_nrml_prsnt

    @allcur_exp_mrg_nrml_prsnt.setter
    def allcur_exp_mrg_nrml_prsnt(self, allcur_exp_mrg_nrml_prsnt):
        """Sets the allcur_exp_mrg_nrml_prsnt of this FundsSucessDataALL.


        :param allcur_exp_mrg_nrml_prsnt: The allcur_exp_mrg_nrml_prsnt of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allcur_exp_mrg_nrml_prsnt = allcur_exp_mrg_nrml_prsnt

    @property
    def allspan_margn(self):
        """Gets the allspan_margn of this FundsSucessDataALL.  # noqa: E501


        :return: The allspan_margn of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allspan_margn

    @allspan_margn.setter
    def allspan_margn(self, allspan_margn):
        """Sets the allspan_margn of this FundsSucessDataALL.


        :param allspan_margn: The allspan_margn of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allspan_margn = allspan_margn

    @property
    def allreal_m2_m_loss(self):
        """Gets the allreal_m2_m_loss of this FundsSucessDataALL.  # noqa: E501


        :return: The allreal_m2_m_loss of this FundsSucessDataALL.  # noqa: E501
        :rtype: str
        """
        return self._allreal_m2_m_loss

    @allreal_m2_m_loss.setter
    def allreal_m2_m_loss(self, allreal_m2_m_loss):
        """Sets the allreal_m2_m_loss of this FundsSucessDataALL.


        :param allreal_m2_m_loss: The allreal_m2_m_loss of this FundsSucessDataALL.  # noqa: E501
        :type: str
        """

        self._allreal_m2_m_loss = allreal_m2_m_loss

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FundsSucessDataALL, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FundsSucessDataALL):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
