# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetProfileSucsessData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'upcoming_plan': 'str',
        'profile': 'Profile'
    }

    attribute_map = {
        'upcoming_plan': 'upcomingPlan',
        'profile': 'profile'
    }

    def __init__(self, upcoming_plan=None, profile=None):  # noqa: E501
        """GetProfileSucsessData - a model defined in Swagger"""  # noqa: E501
        self._upcoming_plan = None
        self._profile = None
        self.discriminator = None
        if upcoming_plan is not None:
            self.upcoming_plan = upcoming_plan
        if profile is not None:
            self.profile = profile

    @property
    def upcoming_plan(self):
        """Gets the upcoming_plan of this GetProfileSucsessData.  # noqa: E501


        :return: The upcoming_plan of this GetProfileSucsessData.  # noqa: E501
        :rtype: str
        """
        return self._upcoming_plan

    @upcoming_plan.setter
    def upcoming_plan(self, upcoming_plan):
        """Sets the upcoming_plan of this GetProfileSucsessData.


        :param upcoming_plan: The upcoming_plan of this GetProfileSucsessData.  # noqa: E501
        :type: str
        """

        self._upcoming_plan = upcoming_plan

    @property
    def profile(self):
        """Gets the profile of this GetProfileSucsessData.  # noqa: E501


        :return: The profile of this GetProfileSucsessData.  # noqa: E501
        :rtype: Profile
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """Sets the profile of this GetProfileSucsessData.


        :param profile: The profile of this GetProfileSucsessData.  # noqa: E501
        :type: Profile
        """

        self._profile = profile

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetProfileSucsessData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetProfileSucsessData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
