# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HistorySuccess(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        's': 'str',
        'c': 'list[float]',
        't': 'list[float]',
        'v': 'list[float]',
        'h': 'list[float]',
        'l': 'list[float]',
        'o': 'list[float]'
    }

    attribute_map = {
        's': 's',
        'c': 'c',
        't': 't',
        'v': 'v',
        'h': 'h',
        'l': 'l',
        'o': 'o'
    }

    def __init__(self, s=None, c=None, t=None, v=None, h=None, l=None, o=None):  # noqa: E501
        """HistorySuccess - a model defined in Swagger"""  # noqa: E501
        self._s = None
        self._c = None
        self._t = None
        self._v = None
        self._h = None
        self._l = None
        self._o = None
        self.discriminator = None
        if s is not None:
            self.s = s
        if c is not None:
            self.c = c
        if t is not None:
            self.t = t
        if v is not None:
            self.v = v
        if h is not None:
            self.h = h
        if l is not None:
            self.l = l
        if o is not None:
            self.o = o

    @property
    def s(self):
        """Gets the s of this HistorySuccess.  # noqa: E501


        :return: The s of this HistorySuccess.  # noqa: E501
        :rtype: str
        """
        return self._s

    @s.setter
    def s(self, s):
        """Sets the s of this HistorySuccess.


        :param s: The s of this HistorySuccess.  # noqa: E501
        :type: str
        """

        self._s = s

    @property
    def c(self):
        """Gets the c of this HistorySuccess.  # noqa: E501


        :return: The c of this HistorySuccess.  # noqa: E501
        :rtype: list[float]
        """
        return self._c

    @c.setter
    def c(self, c):
        """Sets the c of this HistorySuccess.


        :param c: The c of this HistorySuccess.  # noqa: E501
        :type: list[float]
        """

        self._c = c

    @property
    def t(self):
        """Gets the t of this HistorySuccess.  # noqa: E501


        :return: The t of this HistorySuccess.  # noqa: E501
        :rtype: list[float]
        """
        return self._t

    @t.setter
    def t(self, t):
        """Sets the t of this HistorySuccess.


        :param t: The t of this HistorySuccess.  # noqa: E501
        :type: list[float]
        """

        self._t = t

    @property
    def v(self):
        """Gets the v of this HistorySuccess.  # noqa: E501


        :return: The v of this HistorySuccess.  # noqa: E501
        :rtype: list[float]
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this HistorySuccess.


        :param v: The v of this HistorySuccess.  # noqa: E501
        :type: list[float]
        """

        self._v = v

    @property
    def h(self):
        """Gets the h of this HistorySuccess.  # noqa: E501


        :return: The h of this HistorySuccess.  # noqa: E501
        :rtype: list[float]
        """
        return self._h

    @h.setter
    def h(self, h):
        """Sets the h of this HistorySuccess.


        :param h: The h of this HistorySuccess.  # noqa: E501
        :type: list[float]
        """

        self._h = h

    @property
    def l(self):
        """Gets the l of this HistorySuccess.  # noqa: E501


        :return: The l of this HistorySuccess.  # noqa: E501
        :rtype: list[float]
        """
        return self._l

    @l.setter
    def l(self, l):
        """Sets the l of this HistorySuccess.


        :param l: The l of this HistorySuccess.  # noqa: E501
        :type: list[float]
        """

        self._l = l

    @property
    def o(self):
        """Gets the o of this HistorySuccess.  # noqa: E501


        :return: The o of this HistorySuccess.  # noqa: E501
        :rtype: list[float]
        """
        return self._o

    @o.setter
    def o(self, o):
        """Sets the o of this HistorySuccess.


        :param o: The o of this HistorySuccess.  # noqa: E501
        :type: list[float]
        """

        self._o = o

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistorySuccess, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistorySuccess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
