# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class OrderHistorySuccess(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'info_id': 'str',
        'info_msg': 'str',
        'timestamp': 'float',
        'data': 'OrderHistoryData'
    }

    attribute_map = {
        'info_id': 'infoID',
        'info_msg': 'infoMsg',
        'timestamp': 'timestamp',
        'data': 'data'
    }

    def __init__(self, info_id=None, info_msg=None, timestamp=None, data=None):  # noqa: E501
        """OrderHistorySuccess - a model defined in Swagger"""  # noqa: E501
        self._info_id = None
        self._info_msg = None
        self._timestamp = None
        self._data = None
        self.discriminator = None
        self.info_id = info_id
        self.info_msg = info_msg
        self.timestamp = timestamp
        self.data = data

    @property
    def info_id(self):
        """Gets the info_id of this OrderHistorySuccess.  # noqa: E501


        :return: The info_id of this OrderHistorySuccess.  # noqa: E501
        :rtype: str
        """
        return self._info_id

    @info_id.setter
    def info_id(self, info_id):
        """Sets the info_id of this OrderHistorySuccess.


        :param info_id: The info_id of this OrderHistorySuccess.  # noqa: E501
        :type: str
        """
        if info_id is None:
            raise ValueError("Invalid value for `info_id`, must not be `None`")  # noqa: E501

        self._info_id = info_id

    @property
    def info_msg(self):
        """Gets the info_msg of this OrderHistorySuccess.  # noqa: E501


        :return: The info_msg of this OrderHistorySuccess.  # noqa: E501
        :rtype: str
        """
        return self._info_msg

    @info_msg.setter
    def info_msg(self, info_msg):
        """Sets the info_msg of this OrderHistorySuccess.


        :param info_msg: The info_msg of this OrderHistorySuccess.  # noqa: E501
        :type: str
        """
        if info_msg is None:
            raise ValueError("Invalid value for `info_msg`, must not be `None`")  # noqa: E501

        self._info_msg = info_msg

    @property
    def timestamp(self):
        """Gets the timestamp of this OrderHistorySuccess.  # noqa: E501


        :return: The timestamp of this OrderHistorySuccess.  # noqa: E501
        :rtype: float
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this OrderHistorySuccess.


        :param timestamp: The timestamp of this OrderHistorySuccess.  # noqa: E501
        :type: float
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def data(self):
        """Gets the data of this OrderHistorySuccess.  # noqa: E501


        :return: The data of this OrderHistorySuccess.  # noqa: E501
        :rtype: OrderHistoryData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this OrderHistorySuccess.


        :param data: The data of this OrderHistorySuccess.  # noqa: E501
        :type: OrderHistoryData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderHistorySuccess, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderHistorySuccess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
