# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrderHistoryRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instrument': 'str',
        'ord_id': 'str'
    }

    attribute_map = {
        'instrument': 'instrument',
        'ord_id': 'ordId'
    }

    def __init__(self, instrument=None, ord_id=None):  # noqa: E501
        """OrderHistoryRequest - a model defined in Swagger"""  # noqa: E501
        self._instrument = None
        self._ord_id = None
        self.discriminator = None
        self.instrument = instrument
        self.ord_id = ord_id

    @property
    def instrument(self):
        """Gets the instrument of this OrderHistoryRequest.  # noqa: E501


        :return: The instrument of this OrderHistoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._instrument

    @instrument.setter
    def instrument(self, instrument):
        """Sets the instrument of this OrderHistoryRequest.


        :param instrument: The instrument of this OrderHistoryRequest.  # noqa: E501
        :type: str
        """
        if instrument is None:
            raise ValueError("Invalid value for `instrument`, must not be `None`")  # noqa: E501

        self._instrument = instrument

    @property
    def ord_id(self):
        """Gets the ord_id of this OrderHistoryRequest.  # noqa: E501


        :return: The ord_id of this OrderHistoryRequest.  # noqa: E501
        :rtype: str
        """
        return self._ord_id

    @ord_id.setter
    def ord_id(self, ord_id):
        """Sets the ord_id of this OrderHistoryRequest.


        :param ord_id: The ord_id of this OrderHistoryRequest.  # noqa: E501
        :type: str
        """
        if ord_id is None:
            raise ValueError("Invalid value for `ord_id`, must not be `None`")  # noqa: E501

        self._ord_id = ord_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderHistoryRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderHistoryRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
